apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-api-space
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}                # applique la règle à tous les pods du namespace
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: redis
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kafka
        - namespaceSelector:
            matchLabels:
              name: api-space
        - namespaceSelector:
            matchLabels:
              name: istio-system
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53