apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-from-app-space
  namespace: {{ .Values.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["app-space"]
